source/app.d

- only act on current PR (the one w/ the webhook)
- cancel all pending PR builds when a PR get merged (it gets retested after the merge anyhow)

improve build cancelling

---

source/app.d

I believe this could be and issue with mention-bot and Bugzilla comment conflicting itself.
Note that due to the missing tests, this change is done more or less "blindly" trusting the API docs:
https://developer.github.com/v3/issues/comments/

Only update bugzilla comments

---

source/app.d

Not sure whether all reference types do a proper "deep" comparison nowadays, but it would still be more expensive than necessary.

compare native types not Json

---

source/app.d

- and always debounce last check time (to avoid busy polling on failure)

run full auto-merge search asynchronously

---

source/dlangbot/app.d
source/dlangbot/github.d
test/comments.d
test/trello.d
test/utils.d

The idea is to label all bug fixes, s.t. reviewers can filter for them easier. This is often done atm manually.
One good use case is to search for bug fixes prior to the end of the merge window / new releases.

Add bugfix label

---

source/dlangbot/app.d
source/dlangbot/github.d

On "needs work" and "needs rebase" are commonly used to mark an PR as "inactive" (aka depending on user interaction):
https://github.com/dlang/phobos/pulls?q=is%3Aopen+is%3Apr+label%3A%22needs+rebase%22
https://github.com/dlang/phobos/pulls?q=is%3Aopen+is%3Apr+label%3A%22needs+work%22
Thus as a simple first step, this will remove these labels as well when they are existent.
Small gotchas
------------------
- AFAIK DMD and Druntime use different labels atm (e.g. DMD has only "Needs Work")
- I think a new push usually displays a contributor interaction and it can be assumed that the required work was done and the PR can go back into the review queue.

Remove 'needs rebase' and 'needs work' on new push

---

source/dlangbot/app.d
source/dlangbot/github.d
test/labels.d
test/utils.d

Problem: users don't have the permission to add labels.
The idea is simple: the bot parses the PR title for a pre-approved list, e.g.
[Trivial] -> add "Trivial" label
Currently this function will get checked "open" or edited" events.
Gotchas:
- There wasn't an edited hook payload in the data set (should be similar to open though)
- For now it doesn't remove these added labels (but this is seldom required anyways)

Fix #53 - recognize common attributes in the PR title

---

README.md

If someone doesn't want to test a regex bit git force-pushing, this is a useful website. The link opens the used RegEx on Regex101.

Add link to Regex101

---

source/dlangbot/app.d

We could also go for two minutes, but I think I doesn't matter much in terms of used requests per hour and it gives people a more "real-time" experience

Reduce throttled limit to one minute

---

source/dlangbot/github.d
test/comments.d
test/labels.d

@WebDrake - I hope you still have time & motivation:
> Assuming that the bot can be relied on to be 'first responder' to any PR, I'm happy to try to draft an alternative text for it to post (and maybe also look at what texts it can link to).
Here's a proof of concept change that would make the dlang-bot show such a "hello contributor" message.
I didn't adapt the test suite as this PR is just to show that's rather trivial to add such a message ;-)
@MartinNowak what's your opinion on this? If there are people who consider this as too noisy, they could configure a filter at their mail server or simply block the dlang-bot user. OTOH it might be quite motivating and helpful to have a handy summary of important links. Moreover, the dlang-bot is already comments on about half of all dlang PRs. …

[Proof of concept] Show hello greeting message

---

source/dlangbot/github.d
test/comments.d

Now we always update the first & only comment (the filtering leads to duplicate posting).

Avoid duplicate comments

---

data/payloads/bugzilla_buglist.cgi?bug_id=16794&ctype=csv&columnlist=short_desc
data/payloads/bugzilla_buglist.cgi?bug_id=16794&ctype=csv&columnlist=short_desc,bug_status,resolution,bug_severity,priority
data/payloads/bugzilla_buglist.cgi?bug_id=8573&ctype=csv&columnlist=short_desc
data/payloads/bugzilla_buglist.cgi?bug_id=8573&ctype=csv&columnlist=short_desc,bug_status,resolution,bug_severity,priority
source/dlangbot/app.d
source/dlangbot/bugzilla.d
source/dlangbot/github.d
source/dlangbot/warnings.d
test/comments.d
test/trello.d

A first attempt to show helpful warnings (or errors) to a PR submitter (#8).
- In the first commit this adds `warnings.d` where in the future more warning generator can lay. This commit doesn't modify the output.
- The second commit extends the bugzilla query by requesting more attributes (e.g. severity)
- The third commit combines the first two and emits a warnings when a critical/major/regression/blocking PR isn't based onto stable
Again this is meant as first iteration and we probably have to fine tune this (and can hopefully add more warning generators).
One refactoring step that we should do in any case is to find a common "Cache" format for all information already requested by the diverse APIs - passing them around as function parameters doesn't scale that well.

Show warnings in comment (for now: regression PR not against master)

---

source/dlangbot/app.d
source/dlangbot/github.d

I am having a really hard to to see whether everything is work as supposed.
In any case, logging is cheap and it's better to have the history in case something didn't go as expected ...

Add more logging

---

test/utils.d

I had some problems on my machine with port 9001 being blocked.
There's no reason in using fixed ports, let's better pick free ones that work!

Pick free ports for the test suite randomly

---

source/dlangbot/github.d

See https://github.com/dlang-bots/dlang-bot/issues/92

Fix #92 - Use Markdown instead of HTML in greeter message

---

source/dlangbot/app.d
test/comments.d

Rather trivial.
At this point we don't know about the existing labels, even though we have requested it before.
I will change our GH API in another PR to use internal caching and thus avoid this unnecessary request (it doesn't really hurt for now though).

Fix #65 - the Dlang-Bot should use the 'Enhancement' label

---

source/dlangbot/app.d
source/dlangbot/github.d
source/dlangbot/github_api.d

The short-term goal is to separate the code logic from the API, s.t. we can add a caching layer inbetween. Of course, an alternative to caching would be https://github.com/CyberShadow/GHDaemon.
The long-term goal is to create a reusable Dub package out of it.

Move GitHub API code to separate module

---

Procfile

This will log debug messages on Heroku as well.
- We have a free logging addon that allows to search logs anyway
- In case of a misbehavior more information is always appreciated
- Usually only the last few hours, maybe days are relevant anyhow
Vibed:
```
-v --verbose        Enables diagnostic messages (verbosity level 1).
--vv, --vverbose Enables debugging output (verbosity level 2).
--vvv            Enables high frequency debugging output (verbosity level
3).
--vvvv           Enables high frequency trace output (verbosity level 4).
```
Verbosity level 2 is `LogLevel.debug_`:
https://github.com/rejectedsoftware/vibe.d/blob/master/core/vibe/core/log.d#L173

Increase verbosity on Heroku (-vv)

---

source/dlangbot/app.d

I have seen that the comment of the dlang-bot isn't universally popular, so let's make the bot's feature opt-in. As the bot isn't very well used atm, a simple hard-coded list should do fine.
CC @BBasile

Only comment for repos of dlang & dlang-bots GH organizations

---

source/dlangbot/github.d
source/dlangbot/warnings.d
test/comments.d

From https://github.com/dlang/dmd/pull/6928#issuecomment-312481565.
I didn't use UPPERCASE as the other headings don't use UPPERCASE and it looked a bit weird.
-----
-----
We might also opt for a table format like [Danger uses](https://github.com/dlang-bots/dlang-bot/issues/8#issuecomment-279986625).

Let warnings stand out more

---

README.md

From https://github.com/dlang/phobos/pull/5543

Explain Dlang-Bot's cross for references

---

source/dlangbot/github.d
test/comments.d

People repeatedly have shown problems to recognize that a cross (✗)
means that the PR won't be automatically closed (and shown as part of the changelog).
While this has been documented in #124, the best solution is to directly display the meaning
on the Bot's comment.
Follow-up to https://github.com/dlang-bots/dlang-bot/pull/124#issuecomment-313382374

Rename Fix to Auto-Close

---

.travis.yml

Issue: https://issues.dlang.org/show_bug.cgi?id=17614
Temporarily disabling, s.t. auto-merge finally works again

Disable DMD beta until issue 17608 is fixed

---

.travis.yml

- LDC 1.3.0 got released
- DMD 2.075.0-b4 should fix the __VERSION__ regression in Vibe.d

Remove allowed_failures

---

data/hooks/github/dlang_phobos_synchronize_4921.json
source/dlangbot/app.d
source/dlangbot/github.d
test/comments.d

Discovered a small issue during this (see the second commit - the bot previously tried to send an auto-merge immediately on a synchronize event. We never noticed this because luckily the GH required checks prevented this form becoming an issue)

Fix #119 - Don't edit the Bot's comment if the PR has been closed/merged

---

source/dlangbot/app.d
source/dlangbot/warnings.d
test/comments.d

See https://github.com/dlang-bots/dlang-bot/issues/138

Fix #138 - Warning regression fix should always target stable should only be shown for PRs that close open issues

---

dub.sdl
dub.selections.json
source/dlangbot/app.d

Time to upgrade to Vibe.d 0.8.0
(done via `dub upgrade`)

Upgrade DUB dependencies

---

dub.sdl
dub.selections.json
source/dlangbot/app.d

Reverts dlang-bots/dlang-bot#137
The logs don't look good:
As this was the only change in the last days, let's better revert this for now

Revert "Upgrade DUB dependencies"

---

.gitignore
.travis.yml
dub.sdl
dub.selections.json

- use --single for now as tests are neither random- nor parallelizable atm.
also see #167, improves finding failing tests and allows to (re-)run single tests.
```sh
dub test -- --single --trace comments
dub test -- --single --trace comments.remove-auto-merge-on-sync
```

unit-threaded for the win

---

source/dlangbot/github.d
test/labels.d
test/review.d
test/status.d

This should fix https://github.com/dlang-bots/dlang-bot/issues/77
The problem is that we fetch the head sha explicitly from GitHub and then send it
to them in the `tryMerge` method.
I don't know why exactly it sometimes fails (DMD doesn't require reviews), but
fetching the SHA in a separate request just to immediately send it to the GH API
isn't really "safe" anyways and apparentely it also causes problems.

Disable sending the sha explicitly to GitHub on tryMerge

---

source/dlangbot/github.d
test/labels.d
test/review.d
test/status.d

Reverts dlang-bots/dlang-bot#173
Apparently the sha is required:
> PUT https://api.github.com/repos/dlang/dmd/pulls/7752/merge failed; Unprocessable Entity 422.

Revert "Disable sending the sha explicitly to GitHub on tryMerge"

---

source/dlangbot/app.d

The GH API is currently often failing due to rate limits, this works around this problem for now.

Catch exceptions from the Twitter notification + call before GitHub API calls

---

source/dlangbot/github.d

CC @CyberShadow
FYI: I think the `v3.0.0-alpha-5` tag is a bit outdated and currently doesn't work anymore, so maybe you can get around tagging a new release? Thanks!

Add advice on how to test a PR locally

---

dub.selections.json

This is to ensure the Jenkins CI passes at https://github.com/dlang/phobos/pull/6515

Upgrade stdx.allocator to 2.77.2

---

source/dlangbot/app.d
source/dlangbot/bugzilla.d
test/bugzilla.d
test/comments.d
test/utils.d

Here's a first (untested) draft for the Bugzilla integration.
Any thoughts on how to test this?
Some things left to do:
- What if the issue is already closed? Need to check if the Bugzilla API errors out. We should post a comment regardless.
- Check the comment formatting and see if we want to put any more data there, such as the commit message which contains the reference to the bug in question. Will need to split up closing per-issue instead of in bulk.
- Needs the Bugzilla auth in environment as for the other services.

Move in Bugzilla integration

---

source/dlangbot/app.d

This comment shouldn't have been posted, but was posted because the merge commit also "mentions" the fixed issue:
https://issues.dlang.org/show_bug.cgi?id=19687#c3

dlangbot.app: Skip merge commits when deciding whether to ping Bugzilla

---

source/dlangbot/github.d

When running "dub run digger" with a clean cache, recent Dub versions now show:
Package 'digger' was not found locally but is available online:
---
Description: A tool to build D and bisect old D versions
Version: 3.0.0-alpha-9
---
Do you want to fetch 'digger' now? [Y/n]:
This makes the line mostly redundant, so remove it to save vertical space.

dlangbot.github: Omit "dub fetch digger"

---

source/dlangbot/app.d

Trying to compile this module with an alternative libc,
such as Musl, resulted in a compile error because of the
selective import.

Only try to registerMemoryHandler when possible

---

test/cronjob.d
test/utils.d

unit-threaded was complained with the following message:
> Warning:
> testCronDaily passes the criteria for a value-parameterized test
> function but doesn't have the appropriate value UDAs.
> Consider changing its name or annotating it with @DontTest

Test: Rename utility function to work around warning

---

source/dlangbot/bugzilla.d

Allow placing the line later in the commit body, instead of requiring it to be at the start of the commit summary.

dlangbot.bugzilla: Allow matching "Fix issue..." at the start of a line

---

source/dlangbot/github.d
test/comments.d

- creates notifications that seem fairly pointless given that people just created the PR
- not sure people with mail workflows have a different perspective on this

stop mentioning users when they create a PR

---

source/dlangbot/github_api.d

```
Fixes deserialization of events for when a pull request review is 
dismissed.
Hypothetically should fix auto-merging when someone dismisses the last
review requesting changes and all other conditions for auto-merge are
satisfied.
```

dlangbot.github_api: Add GHReview.State.DISMISSED

---

source/dlangbot/app.d
source/dlangbot/database.d

Fix cycle date + add dkorpel to the list of foundation members

---

source/dlangbot/app.d
views/contributor_stats_cycle.dt

Start new bugzilla cycle

---

.github/workflows/ci.yml
README.md

If an unhandled exception occurs in a vibe-core asynchronous task, it will never be displayed, because:
1. `unit-threaded` buffers output (`std.stdio.stdout` is reopened to `/dev/null`)
2. vibe.d calls `abort` after trying to print the exception.
Work around this by updating our documentation and CI commands to use `--debug`, which disables `unit-threaded` output mucking.

Use unit-threaded --debug switch
