dlang/dlang-bot

- dub.selections.json
- source/app.d
I think @lodo1995 discovered that it is quite difficult to get the bug annotation for an already submitted PR. As far as I understand the problem was that rebases aren't parsed, is this correct @lodo1995?
> failure to parse Issue ref

- source/app.d
Big PRs that merge fixes from stable to master move the corresponding cards back from done to testing.
> Don't move Trello cards for merges from stable to master

- source/app.d
https://github.com/dlang/druntime/pull/1696
- https://trello.com/c/kzl7lfqG/205-issue-16080-reg2-071-0-internal-error-backend-cgobj-c-3406-when-building-static-library
- https://trello.com/c/EqS1nlVB/213-issue-16316-reg-2-071-import-deprecation-fully-qualified-name-of-imports-in-mixin-template-not-accessible
- https://trello.com/c/1bH7UUEf/209-issue-15900-reg-2-071-import-deprecation-public-import-ignored-when-using-fully-qualified-name
> PR moved lots of wrong cards from an archived Done list to testing

- .gitignore
> [Trivial] Add test executable to the .gitignore

- dub.selections.json
Bumping dependencies and thus fixing the build error on Travis
> Upgrade vibe.d to v0.7.31-rc.2

- source/dlangbot/github.d
> Cleanup merge artifacts

- source/dlangbot/github.d
> Fix #88,#30 - hardcode Bugzilla repos and warn if no Bugzilla issue is referenced

- Procfile
> Use --vv in Profile

- data/payloads/github_orgs_dlang_public_members?per_page=100
- source/dlangbot/github.d
- test/comments.d
- test/labels.d
- test/trello.d
While not scaling for in the long term, it should take a long time until the Phobos organization has 100 members (currently 32 public members).
> Fix #94 - Improve Improve contributor/owner detection

- test/trello.d
Trivial follow-up to https://github.com/dlang-bots/dlang-bot/pull/100
> Re-enable trello tests

- README.md
> Document current features of Dlang-Bot

- README.md
From https://github.com/rejectedsoftware/vibe.d/pull/1816#issuecomment-313059045 - probably a good idea to document the setup.
> Add guide to configure the Dlang-Bot

- README.md
It seems that many people aren't aware of this ...
> Explain that mentioning multiple issues is possible

- source/dlangbot/github.d
- source/dlangbot/github_api.d
Yet another step at making the GH API more general-purpose (more PRs to come)
This basically just adds more type serialization.
> Add GHIssue, GHLabel, GHMilestone and extend GHRepo

- source/dlangbot/app.d
- source/dlangbot/github_api.d
In-between there have been minor changes that lead to a broken build after #101.
> Update serialization after #101

- source/dlangbot/app.d
See also: https://github.com/dlang/druntime/pull/1830#issuecomment-315572538
> Add simple codecov_hook endpoint to log received messages

- source/dlangbot/warnings.d
- test/comments.d
As I think many people aren't aware of this excellent document:
> https://github.com/dlang/DIPs/blob/master/DIPs/archive/DIP75.md#branching-strategy
> Link to release process (DIP75) on stable warnings

- data/payloads/github_users_ZombineDev
- source/dlangbot/github.d
- test/review.d
The name can be optional as well...
E.g. https://api.github.com/users/MetaLang
Interestingly all users of the auto-merge feature so far had a name.
> Fix merging issue with optional name

- dub.sdl
- dub.selections.json
- source/dlangbot/app.d
Let's try upgrading to Vibe.d 0.8.0 again.
> Revert "Revert "Upgrade DUB dependencies""

- source/dlangbot/github.d
- test/comments.d
Should fix the problem of receiving "Needs work", but checking for "needs work".
> Use sicmp for checkAndRemoveLabels

- source/dlangbot/cron.d
- test/cronjob.d
"blocked" doesn't mean that a PR isn't mergeable, just that either
- one of the required CI is failing
- the PR still requires approval (if the repo requires PRs to be approved)
> Improve mergeableState recognition

- source/dlangbot/bugzilla.d
- to be consistent with GH's Bugzilla integration
#175
> fix #175 - only match first Bugzilla reference

- .travis.yml
- source/dlangbot/app.d
- source/dlangbot/twitter.d
- test/twitter.d
- test/utils.d
This is at the end of all actions, so in case anything fails, it shouldn't matter.
Also I will immediately go ahead and merge this to give it a try live.
Improvements can always be done later and it's encapsulated in its own module if we ever want to remove it or disable it.
> Add a Twitter module to tweet on merged PRs

- source/dlangbot/github.d
Don't mind the CI failures - if this gets approval, I will fix the errors.
> Improve the DLang-Bot message -> convert it into a simple checklist

- source/dlangbot/app.d
- test/twitter.d
Using `@` is a bit problematic on Twitter - people don't have universal usernames :O
> Tweak twitter message

- source/dlangbot/twitter.d
The Twitter API returns "200 OK", but tweets are showing up, hence I change the debugging output to always print the response from the Twitter API.
> Always log the Twitter response body

- .travis.yml
- issue was fixed with 2.078.1 (https://github.com/dlang/dmd/pull/7654)
> remove old workaround

- source/dlangbot/buildkite.d
- test/buildkite.d
- to account for partly finished (running) builds
- no detailed progress estimate for now (just assume 1% done)
> round down the number of needed ci-agents

- data/payloads/hcloud_servers_post
- source/dlangbot/app.d
- source/dlangbot/buildkite.d
- source/dlangbot/hcloud_api.d
- test/buildkite.d
- fix parsing of hcloud server creation
- log checks for server provision/decommission
- some tiny changes
> fixup agent scaling

- source/dlangbot/app.d
- by running it asynchronously
> fix high response times of agent-scaling endpoints

- data/payloads/bugzilla_jsonrpc.cgi_Bug.comments_16794
- data/payloads/bugzilla_jsonrpc.cgi_Bug.comments_17564
- data/payloads/bugzilla_jsonrpc.cgi_Bug.comments_8573
- data/payloads/bugzilla_jsonrpc.cgi_Bug.update_17564
- data/payloads/bugzilla_jsonrpc.cgi_Bug.update_8573
- source/dlangbot/app.d
- source/dlangbot/bugzilla.d
- source/dlangbot/buildkite.d
- test/bugzilla.d
- test/comments.d
- test/trello.d
- test/utils.d
- The event ID is nowhere in the hook payload ...
- Check commit SHA-1. If a comment already mentions that commit, skip
> Continuation of Bugzilla integration

- source/dlangbot/app.d
Required for https://github.com/dlang/dmd/pull/9636
> Add private imports explicitly

- dub.sdl
- dub.selections.json
> Update all dependencies to the latest release

- dub.selections.json
> Upgrade dependencies one more time

- dub.sdl
- dub.selections.json
Needed for https://github.com/dlang/phobos/pull/7545
> Update dependencies to the latest release

- .travis.yml
- README.md
- source/dlangbot/app.d
- test/bugzilla.d
Fixes https://github.com/dlang/dlang-bot/issues/255
> Restrict Bugzilla features to dlang repositories

- source/dlangbot/github.d
- test/bugzilla.d
- test/comments.d
edit: issue is due `|` -> escape description
> Add test case for #236

- source/dlangbot/cron.d
See https://github.com/dlang/phobos/pull/7761
> Remove use of Nullable `alias get this` pending removal.

- source/dlangbot/github.d
- test/comments.d
> Escape backticks with backslashes

- source/dlangbot/app.d
The scoreboard needs to be updated when a PR is merged.
> Fix gamification bug

- source/dlangbot/app.d
- source/dlangbot/database.d
- test/database.d
- views/contributor_stats.dt
I haven't tested the actual web page.
cc @CyberShadow
> Add gamification webpage display + point calculation logic

- source/dlangbot/app.d
> Fix gamification - update database only if the mentioned issue is not closed

- source/dlangbot/app.d
- source/dlangbot/database.d
- views/contributor_stats_cycle.dt
- views/index.dt
> Start a new rewarding cycle + add current cycle page

- views/contributor_stats.dt
- views/contributor_stats_cycle.dt
- views/index.dt
> Fix broken link + align center bugzilla contributors table

- views/contributor_stats_cycle.dt
> Fix date in title (not just address bar)

- source/dlangbot/app.d
- views/contributor_stats_cycle.dt
@CyberShadow maybe leave this for a couple of days before merging. Thanks!
> Start July-October Bugzilla Cycle

- README.md
- data/hooks/trello/active_issue_16794.json
- data/payloads/github_repos_dlang_dmd_pulls_6359_commits
- data/payloads/github_repos_dlang_phobos_pulls_4921_commits
- data/payloads/github_repos_dlang_phobos_pulls_5519_commits
- source/dlangbot/app.d
- source/dlangbot/bugzilla.d
- test/bugzilla.d
- test/comments.d
https://forum.dlang.org/post/gebtpqatonfsgkcqptym@forum.dlang.org
Require all contributors to put the word "Bugzilla" before "Issue", so that the bot understands which bug tracking system is being referenced.
> First phase of GitHub Issues support
